[package]
name = "matching-opencv"
version = "0.1.0"
authors = ["Henning Dieterichs <henning.dieterichs@live.de>"]
edition = "2018"

[dependencies]
opencv = "0.52"
rayon = "1.5.0"
anyhow = "1.0.38"
thread_local = "1.1.3"
matching = { path = "../matching" }
